esphome:
  name: blindcontrol
  includes: src/blindControl.h
  libraries:
  #  Libraries for Bitcino SCS bus
    - http://scsshields.altervista.org/file/espsoftwareserial.zip
    - http://scsshields.altervista.org/file/Biticino_Interfaccia.zip
    
  

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "NNonnaNetz"
  password: "NetzNonna1"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Blindcontrol Fallback Hotspot"
    password: "nFU9fNBcAF76"

captive_portal:
    